### ISSUE TITLE
Indicate completed documents/milestones as locked.

### ISSUE THREAD

**Issue by femmebot** [18F/cfpb-eprocurement#33]
- [x] Append '(locked)' at the end of the status sentence, i.e., "Market research synthesis completed (locked)." 

Accordingly, on the document view, we should indicate somehow that the document is no longer editable. I suggest: 
- [ ] remove the comment field and and submit button
- [ ] append '(locked)' at the end of the document title

**Comment by el-mapache** [comment]
@phoebe I've added this to the top level milestones

**Comment by shawnbot** [comment]
Calling this done, but please re-open if that's not the case.
